<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TaxCloud\Module'                     => __DIR__ . '/Module.php',
    'TaxCloud\Address'                    => __DIR__ . '/src/TaxCloud/Address.php',
    'TaxCloud\BusinessType'               => __DIR__ . '/src/TaxCloud/BusinessType.php',
    'TaxCloud\CartItem'                   => __DIR__ . '/src/TaxCloud/CartItem.php',
    'TaxCloud\ExemptionCertificate'       => __DIR__ . '/src/TaxCloud/ExemptionCertificate.php',
    'TaxCloud\ExemptionCertificateDetail' => __DIR__ . '/src/TaxCloud/ExemptionCertificateDetail.php',
    'TaxCloud\ExemptionReason'            => __DIR__ . '/src/TaxCloud/ExemptionReason.php',
    'TaxCloud\ExemptState'                => __DIR__ . '/src/TaxCloud/ExemptState.php',
    'TaxCloud\State'                      => __DIR__ . '/src/TaxCloud/State.php',
    'TaxCloud\TaxCloud'                   => __DIR__ . '/src/TaxCloud/TaxCloud.php',
    'TaxCloud\TaxID'                      => __DIR__ . '/src/TaxCloud/TaxID.php',
    'TaxCloud\TIC'                        => __DIR__ . '/src/TaxCloud/TIC.php',
    'TaxCloud\TICGroup'                   => __DIR__ . '/src/TaxCloud/TICGroup.php',
    'TaxCloud\TokenHash'                  => __DIR__ . '/src/TaxCloud/TokenHash.php',
    'TaxCloud\VerifiedAddress'            => __DIR__ . '/src/TaxCloud/VerifiedAddress.php',
);
